# Generated by Django 4.2.3 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='highscore',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
