# Generated by Django 4.2.3 on 2023-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_result_gamescore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='total_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
